repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        exclude: modules/
      - id: terraform_tflint
      - id: checkov
        args: [--quiet]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: no-commit-to-branch
        args: [--branch, main]

      # Common errors
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: check-executables-have-shebangs

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
