resources:
  database:
    type: postgres
    options:
      version: 14.2
      class: ${DB_INSTANCE_TYPE}
      storage: ${DB_STORAGE}
      encrypted: ${DB_ENCRYPTED}
      durable: ${DB_MULTI_AZ}
services:
  web:
    build: .
    domain: api.dev.beta.copotrzebne.pl
    health: /api/health
    port: 3000
    resources:
      - database
    environment:
      - PORT=3000
      - "*"
