version: '3.7'

services:
  app:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PORT: ${API_PORT}
      NODE_ENV: ${NODE_ENV}
      API_DB_HOST: postgres
      API_DB_PORT: ${API_DB_PORT}
      API_DB_USERNAME: ${API_DB_USERNAME}
      API_DB_PWD: ${API_DB_PWD}
      API_DB_DATABASE: ${API_DB_DATABASE}
    depends_on:
      - postgres

  # Override using docker-compose.db.yml
  postgres: {}
