version: '3.7'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${API_DB_PWD}
    ports:
      - ${API_DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080