name: Deploy to Dev

on:
  workflow_run:
    workflows: [ "Run Tests" ]
    branches:
      - 'develop'
    types:
      - completed

env:
  # Required by Convox actions
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v1
      - name: login
        id: login
        uses: convox/action-login@v1
        with:
          password: ${{ secrets.CONVOX_DEPLOY_KEY }}
          host: ${{ secrets.CONVOX_HOST }}
      - name: build
        id: build
        uses: convox/action-build@v1
        with:
          rack: dev
          app: api-copotrzebne-pl
      - name: migrate
        id: migrate
        uses: convox/action-run@v1
        with:
          rack: dev
          app: api-copotrzebne-pl
          service: web
          command: yarn db:migrate
          release: ${{ steps.build.outputs.release }}
      - name: promote
        id: promote
        uses: convox/action-promote@v1
        with:
          rack: dev
          app: api-copotrzebne-pl
          release: ${{ steps.build.outputs.release }}
