name: Run Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 17
    - run: yarn install
    - run: yarn build
    - run: yarn start:docker:test-db
    - run: yarn test
    - run: yarn test:e2e
