name: Release

on:
  workflow_run:
    workflows: [ "Run Tests" ]
    branches: [ main ]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
        heroku_app_name: ${{secrets.HEROKU_APP_STAGING}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}